# Generated by Django 4.2.7 on 2023-11-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secondary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerifyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="验证码")),
                ("email", models.EmailField(max_length=32, verbose_name="邮箱")),
                (
                    "send_type",
                    models.CharField(
                        choices=[("register", "注册"), ("forget", "找回密码")],
                        default="register",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "邮箱验证码",
                "verbose_name_plural": "邮箱验证码",
            },
        ),
    ]
