# Generated by Django 4.2.7 on 2023-11-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_remove_user_info_gender_alter_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='name',
            field=models.CharField(max_length=32, verbose_name='账号'),
        ),
    ]
