# Generated by Django 4.2.7 on 2023-11-18 07:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_user_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name="User_Post",
        ),
    ]
