# Generated by Django 4.2.7 on 2023-11-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_submitbug_delete_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitbug',
            name='username',
        ),
        migrations.AddField(
            model_name='submitbug',
            name='submitname',
            field=models.CharField(default='匿名用户', max_length=32, verbose_name='用户名字'),
        ),
    ]
